name: MEGARA
configurations:
  default:
    trim1: [[0,2056],[50,4146]]
    trim2: [[2156,4212],[50,4146]]
    bng: [1,1]
    overscan1: [[0,2056],[4149,4196]]
    overscan2: [[2156,4212],[0,50]]
    prescan1: [[0,2056],[0,50]]
    prescan2: [[2156,4212],[4145,4196]]
    middle1: [[2056,2106],[50,4146]]
    middle2: [[2106,2156],[50,4146]]
  ing:
    trim1: [[0,2056],[52,4148]]
    trim2: [[2156,4212],[48,4144]]
    bng: [1,1]
    overscan1: [[0,2056],[4148,4196]]
    overscan2: [[2156,4212],[0,48]]
    prescan1: [[0,2056],[0,52]]
    prescan2: [[2156,4212],[4144,4196]]
    middle1: [[2056,2106],[53,4144]]
    middle2: [[2106,2156],[49,4144]]
modes:
- date: 2013-11-12
  description: A mode where the recipe successes, used for testing
  key: success
  name: Success
  reference: numina
  status: FINAL
  summary: A mode where the recipe successes
  tagger: null
- date: 2013-11-12
  description: A mode where the recipe fails, used for testing
  key: fail
  name: Fail
  reference: numina
  status: FINAL
  summary: A mode where the recipe fails
  tagger: null
- date: 2012-05-21
  description: Recipe to process bias images
  key: bias_image
  name: Bias Image
  reference: IPUREMI_323
  status: DRAFT
  summary: Recipe to process bias images
  tagger: null
- date: 2012-05-21
  description: Lines and mode lines
  key: dark_image
  name: Dark current Image
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Dark current Image
  uuid: 5b15db30-7774-4823-9645-e8ca27a866af
  tagger: null
- date: 2014-04-23
  description: Lines and mode lines
  key: fiber_flat_image
  name: Fiber Flat Image
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Fiber Flat Image
  uuid: 8a20058f-8887-4b6d-9b65-c113258eccee
  tagger: megaradrp.taggers.tagger_base_image
- date: 2014-04-25
  description: Lines and mode lines
  key: mos_image
  name: Image with the fiber MOS
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Fiber MOS image
  uuid: 6b2ea25b-e6e4-4e0c-b374-825c70387668
  tagger: megaradrp.taggers.tagger_base_image
- date: 2014-04-28
  description: Lines and mode lines
  key: flux_calibration
  name: Pseudo flux-calibration
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Fiber MOS image
  uuid: 9114511f-15d8-40d2-a0b1-e4a6202a3e39
  tagger: megaradrp.taggers.tagger_base_image
- date: 2014-12-10
  description: Lines and mode lines
  key: trace_map
  name: Trace Map
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Fiber MOS image
  uuid: 4e5a5d6f-3bee-4630-836e-0eabdf5e9f9b
  tagger: megaradrp.taggers.tagger_base_image
- date: 2015-05-29
  description: Process an Arc image
  key: arc_calibration
  name: Arc Calibration
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Arc Calibration
  uuid: c1842e00-2005-48bb-9a0e-8a8161f97fdf
  tagger: megaradrp.taggers.tagger_base_image
- date: 2012-05-21
  description: Bad Pixels
  key: bpm
  name: Bad Pixel Mask
  reference: xxx
  status: DRAFT
  summary: Bad Pixel Mask
  uuid: xxxxxx
  tagger: null
- date: 2016-03-03
  description: Slit Flat
  key: slit_flat
  name: Slit Flat
  summary: Slit Flat
  tagger: megaradrp.taggers.tagger_base_image
- date: 2016-03-10
  description: Weights
  key: weights
  name: Weights
  summary: Weights
  tagger: megaradrp.taggers.tagger_base_image
- key: focus_spectrograph
  name: Focus Spectrograph
- date: 2016-04-12
  description: Twillight fiber flat spectrum
  key: twilight_flat_image
  name: Twillight fiber flat
  summary: Twillight fiber flat spectrum
  tagger: megaradrp.taggers.tagger_base_image
- date: 2016-04-20
  description: Image with the LCB
  key: lcb_image
  name: Image with the LCB
  summary: Image with the LCB
  tagger: megaradrp.taggers.tagger_base_image
- date: 2016-05-05
  description: Image with the MOS
  key: mos_image
  name: Image with the MOS
  summary: Image with the MOS
  tagger: megaradrp.taggers.tagger_base_image
- date: 2016-05-06
  description: Extinction Star Recipe
  key: extinction_star
  name: Extinction Star Recipe
  summary: Extinction Star Recipe
  tagger: megaradrp.taggers.tagger_base_image
- date: 2016-05-06
  description: LCB Standard Recipe
  key: lcb_std_star
  name: LCB Standard Recipe
  summary: LCB Standard Recipe
  tagger: megaradrp.taggers.tagger_base_image
- date: 2016-05-06
  description: MOS Standard Recipe
  key: mos_std_star
  name: MOS Standard Recipe
  summary: MOS Standard Recipe
  tagger: megaradrp.taggers.tagger_base_image
- date: 2016-05-06
  description: Sensivity Star Recipe
  key: sensivity_star
  name: Sensivity Star Recipe
  summary: Sensivity Star Recipe
  tagger: megaradrp.taggers.tagger_base_image
- date: 2016-05-06
  description: LCB Fast Mapping Recipe
  key: lcb_fast_mapping
  name: LCB Fast Mapping Recipe
  summary: LCB Fast Mapping Recipe
  tagger: megaradrp.taggers.tagger_base_image
pipelines:
  default:
    version: 1
    recipes:
      arc_calibration: megaradrp.recipes.calibration.arc.ArcCalibrationRecipe
      bias_image: megaradrp.recipes.calibration.bias.BiasRecipe
      bpm: megaradrp.recipes.calibration.bpm.BadPixelsMaskRecipe
      dark_image: megaradrp.recipes.calibration.dark.DarkRecipe
      extinction_star: megaradrp.recipes.scientific.extinctionstar.ExtinctionStarRecipe
      fail: numina.core.utils.AlwaysFailRecipe
      fiber_flat_image: megaradrp.recipes.calibration.flat.FiberFlatRecipe
      flux_calibration: megaradrp.recipes.calibration.fluxcal.PseudoFluxCalibrationRecipe
      focus_spectrograph: megaradrp.recipes.auxiliary.focusspec.FocusSpectrographRecipe
      lcb_fast_mapping: megaradrp.recipes.scientific.lcbfastmapping.LCBFastMappingRecipe
      lcb_image: megaradrp.recipes.scientific.lcb.LCBImageRecipe
      lcb_std_star: megaradrp.recipes.scientific.lcbstdstar.LCBStandardRecipe
      mos_image: megaradrp.recipes.scientific.mos.MOSImageRecipe
      mos_std_star: megaradrp.recipes.scientific.mosstdstar.MOSStandardRecipe
      sensivity_star: megaradrp.recipes.scientific.sensivitystar.SensivityStarRecipe
      slit_flat: megaradrp.recipes.calibration.slitflat.SlitFlatRecipe
      success: numina.core.utils.AlwaysSuccessRecipe
      trace_map: megaradrp.recipes.calibration.trace.TraceMapRecipe
      twilight_flat_image: megaradrp.recipes.calibration.twilight.TwilightFiberFlatRecipe
      weights: megaradrp.recipes.calibration.weights.WeightsRecipe
products:
- name: megaradrp.products.TraceMap
  alias: TraceMap
- name: megaradrp.products.MasterFiberFlat
  alias: MasterFiberFlat
- name: megaradrp.products.MasterSlitFlat
  alias: MasterSlitFlat
- name: megaradrp.products.MasterSensitivity
  alias: MasterSensitivity